Repository evrone/go-clean-template, pull requests merged in 2025-03, with the labels that each got.

#219 fix: make swag-v1 cannot find router.go because of invalid path
  Makefile
Labels: bug

#220 README: controller description mistakes
  README.md
  README_CN.md
  README_RU.md
Labels: bug, documentation

#226 Config: 12-factor config format based on github.com/caarlos0/env/v11
  .env.example
  README.md
  README_CN.md
  README_RU.md
  config/config.go
  config/config.yml
  go.mod
  go.sum
Labels: enhancement, go

#227 Review deps: goccy/go-json; removed abandoned deps from integration tests
  README.md
  README_CN.md
  README_RU.md
  go.mod
  go.sum
  integration-test/integration_test.go
  pkg/httpserver/server.go
  pkg/rabbitmq/rmq_rpc/client/client.go
  pkg/rabbitmq/rmq_rpc/server/server.go
Labels: enhancement, dependencies, go

#228 Bump github.com/jackc/pgx from v4.18.3 to v5.7.2
  go.mod
  go.sum
  pkg/postgres/postgres.go
Labels: dependencies, go

#236 Update README_CN.md
  README_CN.md
Labels: documentation

#241 Bump golang from 1.23.6 to 1.23.7
  Dockerfile
  go.mod
  go.sum
  integration-test/Dockerfile
Labels: dependencies, go, docker

#242 Dockerfile styling
  Dockerfile
  integration-test/Dockerfile
Labels: docker

#243 Bump github.com/rs/zerolog from v1.33.0 to v1.34.0
  go.mod
  go.sum
Labels: dependencies, go

#244 Bump github.com/jackc/pgx/v5 from v5.7.2 to v5.7.3
  go.mod
  go.sum
Labels: dependencies, go

#245 Bump github.com/prometheus
  go.mod
  go.sum
Labels: dependencies, go

#246 Add metrics and swagger configuration to the app
  .env.example
  Makefile
  README.md
  README_CN.md
  README_RU.md
  config/config.go
  docker-compose.yml
  internal/app/app.go
  internal/controller/http/router.go
Labels: documentation, go, docker_compose

#247 Supported for HTTP (fiber) prefork mode configuration
  .env.example
  config/config.go
  docker-compose.yml
  internal/app/app.go
  pkg/httpserver/options.go
  pkg/httpserver/server.go
Labels: go, docker_compose

#248 Update README files with local URLs for health and metrics endpoints
  README.md
  README_CN.md
  README_RU.md
Labels: documentation
